import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";

export default async function MasterUserPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const supabase=await createClient();
  const [{data:profile},{data:store},{data:subscription},{data:logs}]=await Promise.all([supabase.from("profiles").select("id, display_name, email, created_at, last_activity_at").eq("id",id).maybeSingle(),supabase.from("stores").select("id").eq("owner_id",id).maybeSingle(),supabase.from("subscriptions").select("plan, financial_status").eq("user_id",id).maybeSingle(),supabase.from("admin_audit_logs").select("id, action, reason, created_at").eq("affected_user_id",id).order("created_at",{ascending:false}).limit(20)]);
  if(!profile)notFound(); if(store)redirect(`/master/lojas/${store.id}`);
  return <div className="master-content"><Link href="/master" className="master-back">← Voltar</Link><div className="master-detail-title"><div><span>DETALHES DO USUÁRIO</span><h1>{profile.display_name||"Usuário sem nome"}</h1><p>{profile.email||"E-mail indisponível"}</p></div></div><div className="master-user-profile"><section><span>CONTA</span><div className="master-facts"><p><span>Cadastro</span><strong>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"long"}).format(new Date(profile.created_at))}</strong></p><p><span>Última atividade</span><strong>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(profile.last_activity_at))}</strong></p><p><span>Loja</span><strong>Ainda não criada</strong></p><p><span>Plano</span><strong>{subscription?.plan||"Não iniciado"}</strong></p><p><span>Financeiro</span><strong>{subscription?.financial_status||"Sem assinatura"}</strong></p></div></section><section><span>HISTÓRICO</span>{logs?.length?logs.map(log=><article key={log.id}><strong>{log.action.replaceAll("_"," ")}</strong><p>{log.reason||"Sem motivo informado"}</p><small>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(log.created_at))}</small></article>):<div className="master-empty">Nenhuma ação administrativa registrada.</div>}</section></div></div>;
}
