import Link from "next/link";
import { notFound } from "next/navigation";
import { FormMessage } from "@/components/form-message";
import { createClient } from "@/lib/supabase/server";
import { formatMoney } from "@/lib/catalog";

export default async function MasterStorePage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{erro?:string;sucesso?:string}>}) {
  const {id}=await params; const message=await searchParams; const supabase=await createClient();
  const {data:store}=await supabase.from("stores").select("id, owner_id, name, slug, whatsapp, description, is_active, publication_status, created_at, updated_at").eq("id",id).maybeSingle(); if(!store)notFound();
  const [{data:profile},{data:subscription},{data:logs}]=await Promise.all([supabase.from("profiles").select("display_name, email, created_at, last_activity_at").eq("id",store.owner_id).maybeSingle(),supabase.from("subscriptions").select("plan, financial_status, started_at, next_due_at, last_payment_at, grace_period_days, amount_cents, payment_method, internal_notes").eq("store_id",id).maybeSingle(),supabase.from("admin_audit_logs").select("id, action, reason, created_at, previous_value, new_value").eq("affected_store_id",id).order("created_at",{ascending:false}).limit(30)]);
  if(!subscription)notFound(); const dateValue=(value:string|null)=>value?new Date(value).toISOString().slice(0,10):"";
  return <div className="master-content"><Link href="/master" className="master-back">← Voltar</Link><div className="master-detail-title"><div><span>DETALHES DA LOJA</span><h1>{store.name}</h1><p>{profile?.email} · /{store.slug} · {store.whatsapp}</p></div><Link href={`/loja/${store.slug}`} target="_blank">Abrir loja ↗</Link></div><FormMessage error={message.erro} success={message.sucesso}/>
    <div className="master-detail-grid"><section className="master-account-form"><div className="master-section-heading"><span>ASSINATURA</span><h2>Plano e cobrança manual</h2></div><form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="update_subscription"/><div className="form-row"><label className="field"><span>Plano</span><select name="plan" defaultValue={subscription.plan}><option value="monthly">Mensal</option><option value="annual">Anual</option><option value="custom">Personalizado</option></select></label><label className="field"><span>Status financeiro</span><select name="financial_status" defaultValue={subscription.financial_status}><option value="trial">Teste</option><option value="active">Ativo</option><option value="past_due">Vencido</option><option value="suspended">Suspenso</option><option value="cancelled">Cancelado</option></select></label></div><div className="form-row"><label className="field"><span>Próximo vencimento</span><input type="date" name="next_due_at" defaultValue={dateValue(subscription.next_due_at)}/></label><label className="field"><span>Valor cobrado</span><input name="amount" inputMode="decimal" defaultValue={(subscription.amount_cents/100).toFixed(2).replace(".",",")}/></label></div><div className="form-row"><label className="field"><span>Forma de pagamento</span><input name="payment_method" defaultValue={subscription.payment_method??""} placeholder="PIX, boleto, transferência…"/></label><label className="field"><span>Tolerância em dias</span><input type="number" min="0" max="60" name="grace_period_days" defaultValue={subscription.grace_period_days}/></label></div><label className="field"><span>Observações internas</span><textarea name="internal_notes" rows={5} maxLength={5000} defaultValue={subscription.internal_notes??""}/></label><label className="field"><span>Motivo da alteração</span><input name="reason" maxLength={1000} placeholder="Registro interno opcional"/></label><button className="master-primary-action" type="submit">Salvar alterações</button></form></section>
      <aside className="master-side"><section><span>SITUAÇÃO ATUAL</span><div className="master-facts"><p><span>Publicação</span><strong>{store.publication_status}</strong></p><p><span>Financeiro</span><strong>{subscription.financial_status}</strong></p><p><span>Plano</span><strong>{subscription.plan}</strong></p><p><span>Valor</span><strong>{formatMoney(subscription.amount_cents)}</strong></p><p><span>Início</span><strong>{new Intl.DateTimeFormat("pt-BR").format(new Date(subscription.started_at))}</strong></p><p><span>Último pagamento</span><strong>{subscription.last_payment_at?new Intl.DateTimeFormat("pt-BR").format(new Date(subscription.last_payment_at)):"—"}</strong></p><p><span>Última atividade</span><strong>{profile?.last_activity_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(profile.last_activity_at)):"—"}</strong></p></div></section>
        <section><span>AÇÕES RÁPIDAS</span><div className="master-quick-actions">{store.publication_status==="suspended"?<form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="reactivate_store"/><input type="hidden" name="reason" value="Reativação manual"/><button type="submit">Reativar loja</button></form>:store.publication_status==="draft"?<form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="reactivate_store"/><input type="hidden" name="reason" value="Publicação manual"/><button type="submit">Publicar loja</button></form>:<form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="suspend_store"/><input type="hidden" name="reason" value="Suspensão manual"/><button className="danger" type="submit">Suspender loja</button></form>}<form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="confirm_payment"/><input type="hidden" name="next_due_at" value={dateValue(subscription.next_due_at)}/><input type="hidden" name="reason" value="Pagamento confirmado manualmente"/><button type="submit">Marcar pagamento recebido</button></form><form action="/api/master/account" method="post"><input type="hidden" name="store_id" value={id}/><input type="hidden" name="action" value="cancel_account"/><input type="hidden" name="reason" value="Cancelamento manual"/><button className="danger-text" type="submit">Cancelar conta</button></form></div></section>
      </aside></div>
    <section className="master-audit"><div className="master-section-heading"><span>HISTÓRICO ADMINISTRATIVO</span><h2>Alterações recentes</h2></div>{logs?.length?logs.map(log=><article key={log.id}><div><strong>{log.action.replaceAll("_"," ")}</strong><span>{new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(log.created_at))}</span></div><p>{log.reason||"Sem motivo informado."}</p></article>):<div className="master-empty">Nenhuma ação administrativa registrada.</div>}</section>
  </div>;
}
