"use client";

import Image from "next/image";
import Link from "next/link";
import { type FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { activatePush, supportsWebPush } from "@/lib/push-client";
import { useStoreCart } from "@/lib/use-store-cart";

type Product = { id:string; name:string; description:string|null; price_cents:number; sale_price_cents:number|null; track_stock:boolean; stock_quantity:number|null; category:string|null; image_url:string|null };
type Store = { id:string; slug:string; name:string; description:string|null; hero_title:string|null; subtitle:string|null; show_hero_content:boolean; logo_url:string|null; banners:{desktop_url:string;mobile_url:string|null}[]; whatsapp:string; promotions_enabled:boolean };

const money = (cents:number) => new Intl.NumberFormat("pt-BR",{style:"currency",currency:"BRL"}).format(cents/100);
const BagIcon = () => <svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 8h14l1 13H4L5 8Z" stroke="currentColor" strokeWidth="1.5"/><path d="M9 9V6a3 3 0 0 1 6 0v3" stroke="currentColor" strokeWidth="1.5"/></svg>;

export function PublicStorefront({store,products}:{store:Store;products:Product[]}) {
  const [activeCategory,setActiveCategory]=useState("Todos");
  const {cart,changeQuantity,remove,clear,toggle,restored,dismissRestored}=useStoreCart(store.slug,store.id);
  const [cartOpen,setCartOpen]=useState(false);
  const [checkoutOpen,setCheckoutOpen]=useState(false);const [checkoutPending,setCheckoutPending]=useState(false);const [checkoutError,setCheckoutError]=useState<string|null>(null);
  const [activeBanner,setActiveBanner]=useState(0); const touchStartX=useRef<number|null>(null);
  const [promoPrompt,setPromoPrompt]=useState(false); const [pushMessage,setPushMessage]=useState<string|null>(null);
  const [notice,setNotice]=useState<string|null>(null); const noticeTimer=useRef<number|null>(null);
  const categoryRefs=useRef<Record<string,HTMLButtonElement|null>>({});
  const [customerName,setCustomerName]=useState("");const [customerPhone,setCustomerPhone]=useState("");
  const categories=useMemo(()=>["Todos","Novidades",...Array.from(new Set(products.map(product=>product.category).filter((value):value is string=>Boolean(value)))),"Promoções"].filter((value,index,array)=>array.indexOf(value)===index),[products]);
  const visibleProducts=useMemo(()=>products.filter((product,index)=>activeCategory==="Todos"||(activeCategory==="Novidades"&&index<8)||(activeCategory==="Promoções"&&product.sale_price_cents!==null)||product.category===activeCategory),[activeCategory,products]);
  const cartItems=products.filter(product=>cart[product.id]).map(product=>({...product,quantity:cart[product.id]}));
  const count=cartItems.reduce((sum,item)=>sum+item.quantity,0);
  const subtotal=cartItems.reduce((sum,item)=>sum+(item.sale_price_cents??item.price_cents)*item.quantity,0);
  const showNotice=(message:string)=>{setNotice(message);if(noticeTimer.current)window.clearTimeout(noticeTimer.current);noticeTimer.current=window.setTimeout(()=>setNotice(null),2600);};
  const updateQuantity=(id:string,delta:number,name:string)=>{changeQuantity(id,delta);showNotice(delta>0?`${name} adicionado à sacola.`:`Quantidade de ${name} atualizada.`);};
  const addProduct=(id:string,name:string)=>{toggle(id);showNotice(`${name} adicionado à sacola.`);};
  const checkout=async(event:FormEvent<HTMLFormElement>)=>{
    event.preventDefault();setCheckoutPending(true);setCheckoutError(null);const whatsappWindow=window.open("about:blank","_blank");
    const formData=new FormData(event.currentTarget);const tokenKey=`novam-checkout:${store.slug}`;const checkoutToken=localStorage.getItem(tokenKey)??crypto.randomUUID();localStorage.setItem(tokenKey,checkoutToken);
    try{const response=await fetch("/api/public/orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({store_id:store.id,checkout_token:checkoutToken,customer_name:String(formData.get("customer_name")??""),customer_phone:String(formData.get("customer_phone")??""),customer_notes:String(formData.get("customer_notes")??""),items:cartItems.map(item=>({product_id:item.id,quantity:item.quantity}))})});const result=await response.json() as {order?:{order_number:number;subtotal_cents:number;items?:{product_name:string;quantity:number;unit_price_cents:number;line_total_cents:number}[]};error?:string};if(!response.ok||!result.order)throw new Error(result.error||"Não foi possível registrar o pedido.");localStorage.setItem(`novam-customer:${store.slug}`,JSON.stringify({name:customerName,phone:customerPhone}));const lines=(result.order.items??cartItems.map(item=>({product_name:item.name,quantity:item.quantity,unit_price_cents:item.sale_price_cents??item.price_cents,line_total_cents:(item.sale_price_cents??item.price_cents)*item.quantity}))).flatMap(item=>[`${item.quantity}x ${item.product_name}`,`${money(item.unit_price_cents)} cada · ${money(item.line_total_cents)}`,""]);const notes=String(formData.get("customer_notes")??"").trim();const message=[`Olá! Quero finalizar o pedido #${String(result.order.order_number).padStart(4,"0")} na ${store.name}:`,"",...lines,`Total: ${money(result.order.subtotal_cents)}`,"",`Cliente: ${String(formData.get("customer_name"))}`,`WhatsApp: ${String(formData.get("customer_phone"))}`,`Observação: ${notes||"—"}`].join("\n");const url=`https://wa.me/${store.whatsapp.replace(/\D/g,"")}?text=${encodeURIComponent(message)}`;localStorage.removeItem(tokenKey);clear();setCheckoutOpen(false);setCartOpen(false);showNotice("Pedido criado. Abrindo o WhatsApp…");if(whatsappWindow)whatsappWindow.location.assign(url);else window.location.assign(url);}catch(error){whatsappWindow?.close();setCheckoutError(error instanceof Error?error.message:"Não foi possível registrar o pedido.");}finally{setCheckoutPending(false);}
  };
  useEffect(()=>{if(store.banners.length<2)return;const timer=window.setInterval(()=>setActiveBanner(current=>(current+1)%store.banners.length),6000);return()=>window.clearInterval(timer);},[store.banners.length]);
  useEffect(()=>{const timer=window.setTimeout(()=>{try{const saved=JSON.parse(localStorage.getItem(`novam-customer:${store.slug}`)??"{}") as {name?:string;phone?:string};setCustomerName(saved.name??"");setCustomerPhone(saved.phone??"");}catch{/* Ignore invalid local preference. */}if(new URLSearchParams(window.location.search).get("sacola")==="1")setCartOpen(true);},0);return()=>window.clearTimeout(timer);},[store.slug]);
  useEffect(()=>{if(!cartOpen&&!checkoutOpen)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";const close=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!checkoutPending){setCheckoutOpen(false);setCartOpen(false);}};window.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;window.removeEventListener("keydown",close);};},[cartOpen,checkoutOpen,checkoutPending]);
  const moveBanner=(direction:number)=>setActiveBanner(current=>(current+direction+store.banners.length)%store.banners.length);
  useEffect(()=>{
    const key=`novam-promo-prompt:${store.slug}`; const rejected=Number(localStorage.getItem(key)??0); const thirtyDays=30*24*60*60*1000;
    if(!store.promotions_enabled||!supportsWebPush()||!process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY||Notification.permission==="denied"||Date.now()-rejected<thirtyDays)return;
    const timer=window.setTimeout(()=>setPromoPrompt(true),8000); return()=>window.clearTimeout(timer);
  },[store.promotions_enabled,store.slug]);
  const declinePromo=()=>{localStorage.setItem(`novam-promo-prompt:${store.slug}`,String(Date.now()));setPromoPrompt(false);};
  const acceptPromo=async()=>{try{await activatePush(store.id,{promotions:true,cart_reminders:false});setPromoPrompt(false);setPushMessage("Pronto! Você poderá receber novidades desta loja.");window.setTimeout(()=>setPushMessage(null),5000);}catch(error){setPromoPrompt(false);setPushMessage(error instanceof Error&&error.message==="denied"?"Tudo bem. As notificações não foram ativadas.":"As notificações não estão disponíveis neste navegador.");}};
  return <>
    <header className="public-shop-header"><div>{store.logo_url?<Image src={store.logo_url} width={42} height={42} alt={`Logo ${store.name}`}/>:<i>{store.name.slice(0,1)}</i>}<strong>{store.name}</strong></div><nav><a href="#produtos">Produtos</a><a href={`https://wa.me/${store.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">WhatsApp</a></nav><a className="shop-whatsapp-mobile" href={`https://wa.me/${store.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer" aria-label="Falar com a loja no WhatsApp">WhatsApp</a><button className={notice?.includes("adicionado")?"shop-cart-trigger pulse":"shop-cart-trigger"} type="button" onClick={()=>setCartOpen(true)} aria-label={`Abrir sacola com ${count} itens`}><BagIcon/><span>Sacola</span><b>{count}</b></button></header>

    <section className={`public-shop-hero${store.show_hero_content?"":" image-only"}`} onTouchStart={event=>{touchStartX.current=event.touches[0]?.clientX??null;}} onTouchEnd={event=>{if(touchStartX.current===null)return;const distance=(event.changedTouches[0]?.clientX??touchStartX.current)-touchStartX.current;if(Math.abs(distance)>45)moveBanner(distance>0?-1:1);touchStartX.current=null;}}>{store.banners.length>0&&<div className="shop-hero-media">{store.banners.map((banner,index)=><picture key={banner.desktop_url} className={index===activeBanner?"active":""}>{banner.mobile_url&&<source media="(max-width: 700px)" srcSet={banner.mobile_url}/>}<Image src={banner.desktop_url} alt="" width={1920} height={760} priority={index===0} sizes="100vw"/></picture>)}</div>}{store.show_hero_content&&<div className="shop-hero-copy"><span>LOJA OFICIAL</span><h1>{store.hero_title||`${store.name}, do seu jeito.`}</h1><a href="#produtos">Ver coleção</a></div>}{store.banners.length>1&&<div className="shop-hero-controls"><button type="button" onClick={()=>moveBanner(-1)} aria-label="Banner anterior">←</button><div>{store.banners.map((_,index)=><button key={index} type="button" className={index===activeBanner?"active":""} onClick={()=>setActiveBanner(index)} aria-label={`Ver banner ${index+1}`}/>)}</div><button type="button" onClick={()=>moveBanner(1)} aria-label="Próximo banner">→</button></div>}</section>

    {store.subtitle&&<section className="public-shop-subtitle"><span>ENCONTRE O SEU</span><p>{store.subtitle}</p></section>}

    <nav className="shop-categories" aria-label="Categorias de produtos">{categories.map(category=><button ref={element=>{categoryRefs.current[category]=element;}} key={category} type="button" className={activeCategory===category?"active":""} aria-pressed={activeCategory===category} onClick={()=>{setActiveCategory(category);categoryRefs.current[category]?.scrollIntoView({behavior:"smooth",block:"nearest",inline:"center"});}}>{category}</button>)}</nav>

    <section id="produtos" className="public-products"><div className="public-products-heading"><div><span>CATÁLOGO · {activeCategory.toUpperCase()}</span><h2>{activeCategory==="Todos"?"Descubra nossos produtos":activeCategory}</h2></div><p>{visibleProducts.length} {visibleProducts.length===1?"produto":"produtos"}</p></div>
      {visibleProducts.length?<div className="public-product-grid">{visibleProducts.map(product=>{const quantity=cart[product.id]??0;const unavailable=product.track_stock&&(product.stock_quantity??0)<=0;const atLimit=product.track_stock&&quantity>=(product.stock_quantity??0);return <article key={product.id}><div className="public-product-photo"><Link href={`/loja/${store.slug}/produto/${product.id}`} aria-label={`Ver ${product.name}`}>{product.image_url?<Image src={product.image_url} alt={product.name} fill sizes="(max-width:430px) 46vw, (max-width:800px) 48vw, (max-width:1100px) 33vw, 25vw"/>:<span>{product.name.slice(0,1)}</span>}</Link>{unavailable&&<span className="catalog-photo-status">Indisponível</span>}</div><small>{product.category||"Novidades"}</small><h3><Link href={`/loja/${store.slug}/produto/${product.id}`}>{product.name}</Link></h3><div className="catalog-product-price">{product.sale_price_cents!==null&&<del>{money(product.price_cents)}</del>}<strong>{money(product.sale_price_cents??product.price_cents)}</strong></div><div className="catalog-product-action">{unavailable?<span>Produto indisponível</span>:quantity>0?<div className="catalog-quantity" aria-label={`${quantity} unidades na sacola`}><button type="button" onClick={()=>updateQuantity(product.id,-1,product.name)} aria-label={`Remover uma unidade de ${product.name}`}>−</button><strong><b>{quantity}</b><span>{quantity===1?" unidade":" unidades"}</span></strong><button type="button" onClick={()=>updateQuantity(product.id,1,product.name)} disabled={atLimit} aria-label={`Adicionar mais uma unidade de ${product.name}`}>+</button></div>:<button type="button" onClick={()=>addProduct(product.id,product.name)}><span>Adicionar à sacola</span><b>+</b></button>}</div></article>})}</div>:<div className="public-empty"><h2>Nenhum produto nesta categoria.</h2><p>Escolha outra categoria para continuar navegando.</p></div>}
    </section>

    {store.description&&<section className="public-shop-story"><span>SOBRE A LOJA</span><div><h2>{store.name}</h2><p>{store.description}</p></div></section>}

    <footer className="public-shop-footer"><strong>{store.name}</strong><p>Atendimento e finalização pelo WhatsApp.</p><a href={`https://wa.me/${store.whatsapp.replace(/\D/g,"")}`} target="_blank" rel="noreferrer">Falar com a loja →</a></footer>

    <div className={cartOpen?"cart-backdrop visible":"cart-backdrop"} onClick={()=>setCartOpen(false)}/><aside className={cartOpen?"shop-cart-drawer open":"shop-cart-drawer"} aria-hidden={!cartOpen}><div className="cart-drawer-head"><div><span>SUA SACOLA</span><strong>{count} {count===1?"item":"itens"}</strong></div><button type="button" onClick={()=>setCartOpen(false)} aria-label="Fechar sacola">×</button></div>
        <div className="cart-drawer-items">{cartItems.length?cartItems.map(item=><article key={item.id}>{item.image_url?<div className="cart-drawer-photo"><Image src={item.image_url} alt={item.name} fill sizes="88px"/></div>:<div className="cart-drawer-photo empty">{item.name.slice(0,1)}</div>}<div><small>{item.category||"Produto"}</small><strong>{item.name}</strong><span>{money(item.sale_price_cents??item.price_cents)} cada</span><div className="cart-quantity"><button type="button" onClick={()=>updateQuantity(item.id,-1,item.name)} aria-label={`Diminuir quantidade de ${item.name}`}>−</button><b>{item.quantity}</b><button type="button" onClick={()=>updateQuantity(item.id,1,item.name)} disabled={item.track_stock&&item.quantity>=(item.stock_quantity??0)} aria-label={`Aumentar quantidade de ${item.name}`}>+</button></div><em>{money((item.sale_price_cents??item.price_cents)*item.quantity)}</em></div><button className="cart-remove" type="button" onClick={()=>{remove(item.id);showNotice(`${item.name} removido da sacola.`);}}>Remover</button></article>):<div className="cart-empty"><BagIcon/><h2>Sua sacola está vazia.</h2><p>Escolha um produto para começar seu pedido.</p><button type="button" onClick={()=>setCartOpen(false)}>Continuar comprando</button></div>}</div>
      {cartItems.length>0&&<div className="cart-drawer-footer"><button className="cart-continue-shopping" type="button" onClick={()=>setCartOpen(false)}>← Continuar comprando</button><div><span>Subtotal</span><strong>{money(subtotal)}</strong></div><small>O pedido será registrado antes de abrir o WhatsApp.</small><button type="button" onClick={()=>{setCartOpen(false);setCheckoutOpen(true);}}>Continuar pedido <span>→</span></button></div>}
    </aside>
    <div className={checkoutOpen?"checkout-backdrop visible":"checkout-backdrop"} onClick={()=>!checkoutPending&&setCheckoutOpen(false)}/><aside className={checkoutOpen?"checkout-sheet open":"checkout-sheet"} aria-hidden={!checkoutOpen} aria-label="Finalizar pedido"><div className="checkout-sheet-head"><div><span>FINALIZAR PEDIDO</span><h2>Seus dados</h2><p>Usaremos estas informações para identificar o pedido no atendimento.</p></div><button type="button" onClick={()=>setCheckoutOpen(false)} disabled={checkoutPending} aria-label="Fechar">×</button></div><form onSubmit={checkout}><label><span>Nome</span><input name="customer_name" required minLength={2} maxLength={120} autoComplete="name" placeholder="Seu nome" value={customerName} onChange={event=>setCustomerName(event.target.value)}/></label><label><span>WhatsApp com DDD</span><input name="customer_phone" required minLength={8} maxLength={30} type="tel" inputMode="tel" autoComplete="tel" placeholder="(11) 99999-9999" value={customerPhone} onChange={event=>setCustomerPhone(event.target.value)}/></label><label><span>Observações <small>Opcional</small></span><textarea name="customer_notes" maxLength={1000} rows={3} placeholder="Entrega, personalização ou outro detalhe importante."/></label>{checkoutError&&<div className="checkout-error" role="alert">{checkoutError}</div>}<div className="checkout-summary"><span>Total do pedido</span><strong>{money(subtotal)}</strong></div><button type="submit" disabled={checkoutPending} aria-busy={checkoutPending}>{checkoutPending?"Registrando pedido…":"Registrar e abrir WhatsApp"}<span>→</span></button><small>O pagamento e a entrega serão combinados diretamente com a loja.</small></form></aside>
    {restored&&<div className="cart-restored"><div><strong>Seu carrinho continua aqui.</strong><span>Retome a compra de onde parou.</span></div><button type="button" onClick={()=>{dismissRestored();setCartOpen(true);}}>Continuar compra</button><button className="cart-restored-close" type="button" onClick={dismissRestored} aria-label="Fechar">×</button></div>}
    {promoPrompt&&<aside className="store-soft-prompt"><span>NOVIDADES DA LOJA</span><h2>Fique por dentro das novidades</h2><p>Deseja receber promoções, lançamentos ou frete grátis? Ative as notificações e acompanhe esta loja.</p><div><button type="button" onClick={acceptPromo}>Ativar notificações</button><button type="button" onClick={declinePromo}>Agora não</button></div></aside>}
    {pushMessage&&<div className="store-notice">{pushMessage}</div>}
    {notice&&<div className="store-action-toast" role="status" aria-live="polite">{notice}</div>}
  </>;
}
