import Link from "next/link";
import { createClient } from "@/lib/supabase/server";

type Profile={id:string;display_name:string|null;email:string|null;created_at:string;last_activity_at:string};
type Store={id:string;owner_id:string;name:string;slug:string;whatsapp:string;is_active:boolean;publication_status:"draft"|"published"|"suspended";created_at:string};
type Subscription={store_id:string;plan:"monthly"|"annual"|"custom";financial_status:"trial"|"active"|"past_due"|"suspended"|"cancelled";next_due_at:string|null;last_payment_at:string|null;amount_cents:number};
const financialLabels={trial:"Teste",active:"Ativo",past_due:"Vencido",suspended:"Suspenso",cancelled:"Cancelado"};
const storeLabels={draft:"Rascunho",published:"Publicada",suspended:"Suspensa"};

export default async function MasterPage({searchParams}:{searchParams:Promise<{q?:string}>}) {
  const supabase=await createClient(); const {q=""}=await searchParams;
  const [{data:profileData},{data:storeData},{data:subscriptionData},{data:metricData}]=await Promise.all([supabase.from("profiles").select("id, display_name, email, created_at, last_activity_at").order("created_at",{ascending:false}),supabase.from("stores").select("id, owner_id, name, slug, whatsapp, is_active, publication_status, created_at").order("created_at",{ascending:false}),supabase.from("subscriptions").select("store_id, plan, financial_status, next_due_at, last_payment_at, amount_cents"),supabase.rpc("master_alert_metrics")]);
  const profiles=(profileData??[]) as Profile[]; const stores=(storeData??[]) as Store[]; const subscriptions=(subscriptionData??[]) as Subscription[]; const profileMap=new Map(profiles.map(profile=>[profile.id,profile])); const subscriptionMap=new Map(subscriptions.map(subscription=>[subscription.store_id,subscription]));
  const normalized=q.toLowerCase().trim(); const filtered=stores.filter(store=>{const profile=profileMap.get(store.owner_id);return !normalized||[store.name,store.slug,store.whatsapp,profile?.display_name,profile?.email].some(value=>value?.toLowerCase().includes(normalized));});
  const storeMap=new Map(stores.map(store=>[store.owner_id,store])); const filteredProfiles=profiles.filter(profile=>!normalized||[profile.display_name,profile.email,storeMap.get(profile.id)?.name,storeMap.get(profile.id)?.slug].some(value=>value?.toLowerCase().includes(normalized)));
  const metrics=metricData?.[0]??{due_soon:0,overdue:0,suspended_stores:0,trials:0,recent_payments:0};
  return <div className="master-content"><div className="master-title"><div><span>ADMINISTRAÇÃO</span><h1>Usuários e lojas</h1><p>Acompanhe acessos, vencimentos e situação operacional sem misturar finanças com publicação.</p></div><strong>{stores.length} lojas</strong></div>
    <section className="master-alerts"><article><span>Vencem em 7 dias</span><strong>{metrics.due_soon}</strong></article><article><span>Contas vencidas</span><strong>{metrics.overdue}</strong></article><article><span>Lojas suspensas</span><strong>{metrics.suspended_stores}</strong></article><article><span>Usuários em teste</span><strong>{metrics.trials}</strong></article><article><span>Pagamentos recentes</span><strong>{metrics.recent_payments}</strong></article></section>
    <form className="master-search"><input name="q" defaultValue={q} placeholder="Buscar por nome, e-mail, WhatsApp ou slug"/><button type="submit">Pesquisar</button>{q&&<Link href="/master">Limpar</Link>}</form>
    <div className="master-list-label"><span>LOJAS</span><strong>{filtered.length}</strong></div><section className="master-table"><div className="master-table-head"><span>Loja / usuário</span><span>Plano</span><span>Financeiro</span><span>Loja</span><span>Vencimento</span><span>Atividade</span></div>{filtered.length?filtered.map(store=>{const profile=profileMap.get(store.owner_id);const subscription=subscriptionMap.get(store.id);return <Link href={`/master/lojas/${store.id}`} key={store.id} className="master-table-row"><div><strong>{store.name}</strong><span>{profile?.email||"E-mail indisponível"}</span><small>/{store.slug}</small></div><span className="master-plan">{subscription?.plan||"monthly"}</span><span className={`master-status ${subscription?.financial_status||"trial"}`}>{financialLabels[subscription?.financial_status||"trial"]}</span><span className={`master-status ${store.publication_status}`}>{storeLabels[store.publication_status]}</span><span>{subscription?.next_due_at?new Intl.DateTimeFormat("pt-BR").format(new Date(subscription.next_due_at)):"Não definido"}</span><span>{profile?.last_activity_at?new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeStyle:"short"}).format(new Date(profile.last_activity_at)):"—"}</span></Link>}):<div className="master-empty">Nenhuma loja encontrada.</div>}</section>
    <div className="master-list-label users"><span>USUÁRIOS</span><strong>{filteredProfiles.length}</strong></div><section className="master-users-list">{filteredProfiles.length?filteredProfiles.map(profile=>{const store=storeMap.get(profile.id);return <Link href={`/master/usuarios/${profile.id}`} key={profile.id}><div><strong>{profile.display_name||"Usuário sem nome"}</strong><span>{profile.email||"E-mail indisponível"}</span></div><span>{store?.name||"Ainda não criou loja"}</span><span>Criado em {new Intl.DateTimeFormat("pt-BR").format(new Date(profile.created_at))}</span><b>Ver detalhes →</b></Link>}):<div className="master-empty">Nenhum usuário encontrado.</div>}</section>
  </div>;
}
