import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { FormMessage } from "@/components/form-message";
import { formatMoney } from "@/lib/catalog";
import { createClient } from "@/lib/supabase/server";

const statusLabels={new:"Novo",confirmed:"Confirmado",completed:"Concluído",cancelled:"Cancelado"} as const;
type Status=keyof typeof statusLabels;
type OrderItem={id:string;product_name:string;sku:string|null;unit_price_cents:number;quantity:number;line_total_cents:number;order_item_options:{id:string;option_name:string;option_value:string}[]};
type Order={id:string;order_number:number;status:Status;customer_name:string;customer_phone:string;customer_notes:string|null;subtotal_cents:number;total_cents:number;created_at:string;order_items:OrderItem[]};

export default async function OrderDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const {id}=await params;const message=await searchParams;const supabase=await createClient();const {data:{user}}=await supabase.auth.getUser();if(!user)redirect("/login");const {data:store}=await supabase.from("stores").select("id").eq("owner_id",user.id).maybeSingle();if(!store)redirect("/painel");
  const {data}=await supabase.from("orders").select("id, order_number, status, customer_name, customer_phone, customer_notes, subtotal_cents, total_cents, created_at, order_items(id, product_name, sku, unit_price_cents, quantity, line_total_cents, order_item_options(id, option_name, option_value))").eq("id",id).eq("store_id",store.id).maybeSingle();if(!data)notFound();const order=data as unknown as Order;
  return <div className="dashboard-content subpage-content"><div className="edit-product-back"><Link href="/painel/pedidos">← Voltar para pedidos</Link></div><div className="dashboard-topbar"><div><p>Detalhes do pedido</p><h1>Pedido #{String(order.order_number).padStart(4,"0")}</h1></div><div className="store-status is-active"><span/>{statusLabels[order.status]}</div></div><p className="dashboard-intro">Criado em {new Intl.DateTimeFormat("pt-BR",{dateStyle:"long",timeStyle:"short"}).format(new Date(order.created_at))}</p><FormMessage error={message.erro} success={message.sucesso}/><div className="order-detail-grid"><section className="order-detail-main"><div className="order-detail-section-head"><span>ITENS DO PEDIDO</span><strong>{order.order_items.reduce((sum,item)=>sum+item.quantity,0)} itens</strong></div>{order.order_items.map(item=><article key={item.id}><div><strong>{item.quantity}× {item.product_name}</strong>{item.sku&&<small>SKU {item.sku}</small>}{item.order_item_options.map(option=><small key={option.id}>{option.option_name}: {option.option_value}</small>)}</div><div><span>{formatMoney(item.unit_price_cents)} cada</span><strong>{formatMoney(item.line_total_cents)}</strong></div></article>)}<div className="order-detail-total"><span>Total</span><strong>{formatMoney(order.total_cents)}</strong></div></section><aside className="order-detail-side"><section><span>CLIENTE</span><h2>{order.customer_name}</h2><a href={`https://wa.me/55${order.customer_phone.replace(/\D/g,"").replace(/^55/,"")}`} target="_blank" rel="noreferrer">{order.customer_phone} ↗</a>{order.customer_notes&&<p>{order.customer_notes}</p>}</section><section><span>STATUS</span><form action="/api/orders/status" method="post"><input type="hidden" name="id" value={order.id}/><input type="hidden" name="return_to" value={`/painel/pedidos/${order.id}`}/><select name="status" defaultValue={order.status}>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select><button type="submit">Salvar status</button></form></section></aside></div></div>;
}
